language: python
python:
  - '2.7'
branches:
  only:
    - page
install:
  - pip install -r requirements.txt
script:
  - git submodule update --init --recursive
  - make publish

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  fqdn: venencenter.eu
  keep-history: true
  local-dir: output
  target_branch: master
  on:
    branch: page

